Added enterFullscreen & exitFullscreen methods for Windows
google/flutter-desktop-embedding pull request #859
Opened 2021-06-11 18:28 UTC by alexmercerind

Added `enterFullscreen` & `exitFullscreen` to enter and exit fullscreen mode (for the window containing Flutter instance).

**Usage**
- `enterFullscreen`
```dart
window_size.enterFullscreen();
```
- `exitFullscreen`
Requires final window frame as `Rect`.
```dart
window_size.getWindowInfo().then((window) {
  final screen = window.screen;
  if (screen != null) {
    final screenFrame = screen.visibleFrame;
    final width = math.max((screenFrame.width / 2).roundToDouble(), 800.0);
    final height = math.max((screenFrame.height / 2).roundToDouble(), 600.0);
    final left = ((screenFrame.width - width) / 2).roundToDouble();
    final top = ((screenFrame.height - height) / 3).roundToDouble();
    final frame = Rect.fromLTWH(left, top, width, height);
    window_size.exitFullscreen(frame);
  }
});
```

**Demo**

https://user-images.githubusercontent.com/28951144/121733126-b6b28480-cb10-11eb-9708-b5ac73d3a7ff.mp4

2021-06-11 18:30 UTC, alexmercerind commented
@googlebot I signed it!

2021-06-11 18:37 UTC, alexmercerind commented
I can try to add Linux support aswell.

2021-06-11 20:02 UTC, alexmercerind commented
Added Linux support aswell. Looking forward for any requested changes to get this merged.

Thankyou.

2021-06-12 16:06 UTC, stuartmorgan requested changes
Thanks for the submission. The macOS implementation should be straightforward, so I can add that once this is finished.

2021-06-12 16:06 UTC, stuartmorgan commented on plugins/window_size/windows/window_size_plugin.cpp
> +      flutter::EncodableValue(isChangeSuccessful)
Why is failure being returned as a success? And why do the return semantics of Windows and Linux not match (nor does this match the use on the Dart side, which ignores the return value).

2021-06-12 16:06 UTC, stuartmorgan commented on plugins/window_size/windows/window_size_plugin.cpp
> +    );
Please follow the Google style guide, and the style of the existing code. This code block is violating Google style rules for variable naming, and not following existing conventions of this code (not naming variables their types, specifying global namespace resolution for Win32 calls)

2021-06-12 19:24 UTC, alexmercerind commented
Now I've followed Google code style precisely.

Now `exitFullscreen` no longer requires `frame` parameter and window restores to initial size now after exiting fullscreen.

On windows, there isn't a specific API to use for fullscreen like GTK, so I had to do that.
Now I made it store initial window frame as `RECT` globally before going fullscreen and restore window to that frame upon exiting from fullscreen mode.
As a result, I also improved the Windows implementation by using [this](https://devblogs.microsoft.com/oldnewthing/20100412-00/?p=14353) example.

2021-06-22 17:47 UTC, alexmercerind commented
@stuartmorgan what do i do now? 😟

2021-06-22 19:52 UTC, stuartmorgan commented
@alexmercerind What do you do about what? I'm not sure what the question is.

2021-07-01 13:56 UTC, bdlukaa commented
Any chance of this getting merged soon?

2021-07-01 15:51 UTC, stuartmorgan commented
I need to have time to review it before it can be merged. If you can't wait until that has happened, you can use the PR's branch.

2021-07-28 14:53 UTC, sabin26 commented
@alexmercerind 
When windows button is pressed from keyboard to access the Taskbar after entering full screen, I am unable to view other applications after opening them from the taskbar. The flutter window stays on top of other windows. So, only flutter window is on the front view. Please have a look at it.

2021-08-08 19:27 UTC, stuartmorgan commented
Just wanted to update to say that I haven't forgotten about this, I'm just balancing a lot of priorities, and context switching to two platforms I'm no longer regularly using requires a significant time investment.

/cc @robert-ancell and @clarkezone in case you have time to review your respective platforms of expertise here.

2021-09-07 20:45 UTC, stuartmorgan commented
I apologize that this PR has been in limbo for so long.

After recently taking stock of all of the work across desktop and plugins in general, it's clear that expanding the scope of `window_size` with additional functionality isn't the best use of the Flutter team's resources, so I've [updated the plugin's README](https://github.com/google/flutter-desktop-embedding/blob/master/plugins/window_size/README.md#scope) to lay out the new, more restricted plan for the scope of the plugin. (The long delay on this PR demonstrates the problem with leaving an open-ended scope for a plugin that is in practice very low priority relative to all of the other work.)

Given that new scope, I'm going to close this PR. I encourage you to create a new plugin for this purpose, or to submit it to an existing community-developed window manipulation plugin.

(I understand that it may seem strange not to take an already-written PR based on resourcing considerations, but there is still non-trivial cost in taking the PR; in addition to review, there would undoubtedly be follow-up issues due to interaction with other parts of the API, edge cases with OS behaviors, etc., since full-screen is inherently complex. Having that in a plugin that will get the resources needed to maintain it more actively than we can currently maintain `window_size` will be a better experience for everyone.)

2021-09-07 20:45 UTC, closed without merging